apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Owner.Name }}-tls
  labels:
<<<<<<< HEAD
    app: {{.Orchestrator.Name}}
    component: {{.Orchestrator.Name}}
=======
    app: {{.Owner.Name}}
    component: {{ .Owner.Name }}

>>>>>>> f7cb3c7 (Second round of function standardization (#607))
spec:
  ipFamilies:
    - IPv4
  ports:
    {{if .Owner.Spec.EnableGuardrailsGateway}}
    - name: gateway
      protocol: TCP
      port: {{if .UseAuthProxy}}8490{{else}}8090{{end}}
      targetPort: {{if .UseAuthProxy}}8490{{else}}8090{{end}}
    {{end -}}
    - name: https
      protocol: TCP
      port: {{if .UseAuthProxy}}8432{{else}}8032{{end}}
      targetPort: {{if .UseAuthProxy}}8432{{else}}8032{{end}}
    {{if .UseAuthProxy}}
    - name: https-tls
      protocol: TCP
      port: 8032
      targetPort: 8032
    {{end}}
    - name: health
      protocol: TCP
      port: 8034
      targetPort: 8034
<<<<<<< HEAD
=======
    {{if .Owner.Spec.EnableBuiltInDetectors}}
    - name: detector-metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
    {{end}}
>>>>>>> f7cb3c7 (Second round of function standardization (#607))
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{.Owner.Name}}
    component: {{.Owner.Name}}
