apiVersion: v1
kind: Service
metadata:
  name: {{.Orchestrator.Name}}-service
  namespace: {{.Orchestrator.Namespace}}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Orchestrator.Name }}-tls
  labels:
    app: {{.Orchestrator.Name}}
    component: {{.Orchestrator.Name}}
spec:
  ipFamilies:
    - IPv4
  ports:
    {{if .Orchestrator.Spec.EnableGuardrailsGateway}}
    - name: gateway
      protocol: TCP
      port: {{if .UseOAuthProxy}}8490{{else}}8090{{end}}
      targetPort: {{if .UseOAuthProxy}}8490{{else}}8090{{end}}
    {{end -}}
    - name: https
      protocol: TCP
      port: {{if .UseOAuthProxy}}8432{{else}}8032{{end}}
      targetPort: {{if .UseOAuthProxy}}8432{{else}}8032{{end}}
    - name: health
      protocol: TCP
      port: 8034
      targetPort: 8034
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{.Orchestrator.Name}}
    component: {{.Orchestrator.Name}}
