name: Sync Branch incubation
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    if: github.repository == 'opendatahub-io/trustyai-service-operator'
    runs-on: ubuntu-latest
    name: Syncing branch incubation
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "incubation"
      - name: Add labels
        if: ${{ steps.pull.outputs.PULL_REQUEST_NUMBER != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{steps.pull.outputs.PULL_REQUEST_NUMBER}},
              labels: ['bot/merge-incubation']
            });
